osx_image: xcode8
language: objective-c
podfile: Example/Podfile
before_install:
  - gem install --no-rdoc --no-ri --no-document --quiet cocoapods xcpretty
  - cd Example && pod install && cd -
  - xcodebuild -workspace Example/ODStringify.xcworkspace -list
script:
  - xcodebuild -workspace Example/ODStringify.xcworkspace -scheme ODStringify_Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=9.3' OTHERCFLAGS="-fprofile-arcs -ftest-coverage" clean test | xcpretty
  - xcodebuild -workspace Example/ODStringify.xcworkspace -scheme ODStringify_Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' OTHERCFLAGS="-fprofile-arcs -ftest-coverage" clean test | xcpretty
  - pod lib lint
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - cat -n ~/Library/Logs/scan/*
  - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
  - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
