osx_image: xcode8
language: objective-c
podfile: Example/Podfile
before_install:
  - gem install --no-rdoc --no-ri --no-document --quiet cocoapods xcpretty
  - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -workspace Example/${POD_NAME}.xcworkspace -scheme ${POD_NAME}_Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
  - set -o pipefail && xcodebuild test -workspace Example/${POD_NAME}.xcworkspace -scheme ${POD_NAME}_Example -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - cat -n ~/Library/Logs/scan/*
  - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
  - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
